# ---------------------------------------------------------------
# 方案设置
# ---------------------------------------------------------------

scheme: Gemini

# ---------------------------------------------------------------
# 菜单设置
# ---------------------------------------------------------------

menu:
  开始使用:
    default: /getting-start/ || fa fa-bell
    安装: /installation/ || fa fa-download
    配置: /configuration/ || fa fa-wrench
  主题设置:
    default: /theme-settings/ || fa fa-star
    侧边栏: /sidebar/ || fa fa-bars
    页脚: /footer/ || fa fa-sticky-note
    文章: /posts/ || fa fa-paragraph
    自定义页面: /custom-pages/ || fa fa-swatchbook
    其它设置: /miscellaneous/ || fa fa-university
    国际化: /internationalization/ || fa fa-globe
  第三方服务:
    default: /third-party-services/ || fa fa-suitcase
    数学公式: /math-equations/ || fa fa-square-root-alt
    评论系统: /comment-systems/ || fa fa-comment-alt
    聊天服务: /chat-services/ || fa fa-comments
    本地搜索: /local-search/ || fa fa-search
    外部库: /external-libraries/ || fa fa-lightbulb
  标签插件:
    default: /tag-plugins/ || fa fa-tags
    按钮: /button/ || fa fa-cube
    图片组: /group-pictures/ || fa fa-images
    标记: /label/ || fa fa-pen-square
    链接网格: /link-grid/ || fa fa-grip-vertical
    绘图: /mermaid/ || fa fa-sitemap
    便签: /note/ || fa fa-sticky-note
    PDF: /pdf/ || fa fa-file-pdf
    选项卡: /tabs/ || fa fa-adjust
  高级设置:
    default: /advanced-settings/ || fa fa-cog
    加速服务: /vendors/ || fa fa-plug
    自定义文件: /custom-files/ || fa fa-palette
    Front Matter: /front-matter/ || fa fa-edit
  故障排除: /troubleshooting/ || fa fa-times-circle

# ---------------------------------------------------------------
# 侧边栏设置
# 参见：https://mopsite.github.io/next/theme-settings/sidebar/
# ---------------------------------------------------------------

# 侧边栏头像
avatar:
  # 设置链接以替换默认图像
  url: /images/avatar.svg
  # 如果为 true，头像将显示为圆形
  rounded: true

# 侧边栏显示文章 / 分类 / 标签
site_state: false

# 侧边栏链接管理
links_settings:
  icon:
  title:
  # 链接布局，可用值：block | inline
  layout: block

links:
  Git: https://mopsite.github.io/git
  Hexo: https://mopsite.github.io/hexo
  FontAwesome: https://mopsite.github.io/fontawesome

# ---------------------------------------------------------------
# 页脚设置
# 参见：https://mopsite.github.io/next/theme-settings/footer/
# ---------------------------------------------------------------

footer:
  # 建站年份，如果不设置，则只显示当前年份
  since: 2021

  # 年份和版权之间的图标
  icon:
    # 如果想要动画图标，设置为true
    animated: true

  # 是否显示强力驱动
  powered: false

# ---------------------------------------------------------------
# 其他设置
# 参见：https://mopsite.github.io/next/theme-settings/miscellaneous/
# ---------------------------------------------------------------

codeblock:
  # 代码块高亮主题
  # 所有可用的主题：https://theme-next.js.org/highlight/
  theme:
    light: agate
    dark: agate
  # 代码块复制按钮
  copy_button:
    enable: true
    # 可用值：default | flat | mac
    style: mac

back2top:
  # 返回顶部按钮中显示滚动百分比
  scrollpercent: true

# 阅读进度条
reading_progress:
  enable: true
  # 可用值：top | bottom
  position: bottom

# ---------------------------------------------------------------
# 第三方插件和服务设置
# 参见：https://mopsite.github.io/next/third-party-services/
# 更多插件：https://github.com/next-theme/awesome-next
# 你可能需要安装相应的依赖包
# ---------------------------------------------------------------

# 为你的网站提供快速浏览
# 更多信息：https://github.com/next-theme/pjax
pjax: true

# FancyBox 是一款用来缩放图片的工具
# 更多信息：https://fancyapps.com/fancybox/
fancybox: true

# 盘古之白，用于在中英文之间自动插入空格
# 更多信息：https://github.com/vinta/pangu.js
pangu: true

# 快速链接
# 更多信息：https://getquick.link
quicklink:
  enable: true

# ---------------------------------------------------------------
# 搜索服务
# ---------------------------------------------------------------

# 本地搜索
# 依赖包：https://github.com/next-theme/hexo-generator-searchdb
# 参见：https://mopsite.github.io/next/third-party-services/local-search/

local_search:
  enable: true

# ---------------------------------------------------------------
# 标签插件设置
# 参见：https://mopsite.github.io/next/tag-plugins/
# ---------------------------------------------------------------

# 便签标签
note:
  # 便签标签样式值
  style: flat
  icons: true

# 绘图标签
mermaid:
  enable: true
